os:
  - linux
language: cpp
#  - clang

addons:
  apt:
    packages:
      - doxygen
      - gperf
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check esp code
      script:
        - ./.travis/setup_esp_build_env.sh travis
        - . ~/esp/esp-idf/export.sh
        - git submodule update --init --recursive
        - make defconfig
        - make
      cache:
        directories:
          - /home/travis/esp
          - /home/travis/.espressif

