# This is Makefile for ESP32 IDF

COMPONENT_ADD_INCLUDEDIRS := ./include
COMPONENT_SRCDIRS := ./src
CPPFLAGS += -DSM_ENGINE_MULTITHREAD=1 -DSM_ENGINE_USE_STL=1 -DSM_ENGINE_DYNAMIC_ALLOC=1

# COMPONENT_DEPENDS := spibus
