#pragma once

enum
{
    CLOCK_STATE_HW_INIT,
    CLOCK_STATE_APP_INIT,
    CLOCK_STATE_MAIN,
    CLOCK_STATE_SHOW_IP,
    CLOCK_STATE_SHOW_TEMP,
    CLOCK_STATE_SLEEP,
    CLOCK_STATE_SETUP_TIME,
    CLOCK_STATE_SETUP_ALARM,
    CLOCK_STATE_ALARM,
};

